---
title: "Bird_Speed_Table"
author: "Daina Bouquin"
date: "November 30, 2015"
output: html_document
---

```{r, warning=FALSE, message=FALSE}
library(rvest)
library(stringr)
```

These scripts can be used to scrape a table by copying the table's xpath in the source. 
I obtained this xpath using Chrome's developer tools
```{r, warning=FALSE}
url <- "https://en.wikipedia.org/wiki/List_of_birds_by_flight_speed"

bird_speeds <- url %>%
  html() %>%
  html_nodes(xpath='//*[@id="mw-content-text"]/table[1]') %>%
  html_table()
bird_speeds <- bird_speeds[[1]]

colnames(bird_speeds)
# Rename the columns
colnames(bird_speeds) <- c("bird", "image", "species", "family", "avg_h_speed", "max_h_speed", "avg_d_speed", "max_airspeed", "flight")

head(bird_speeds)
bird_speeds[1,]
```

To clean up the speed columns, I'll remove the citation tags in square brackets using gsub
```{r}
bird_speeds$avg_h_speed <- gsub("\\[(.+)\\]", "", bird_speeds$avg_h_speed)
bird_speeds$max_h_speed <- gsub("\\[(.+)\\]", "", bird_speeds$max_h_speed)
bird_speeds$avg_d_speed <- gsub("\\[(.+)\\]", "", bird_speeds$avg_d_speed)
bird_speeds$max_airspeed <- gsub("\\[(.+)\\]", "", bird_speeds$max_airspeed)
head(bird_speeds)
```

I will also now split up the speed columns so that there are separate columns for mph and km and the units aren't embedded in the data

