---
title: "War Pigeons Vs Raceing Pigeons"
author: "Nabila Hossain"
date: "December 10, 2015"
output: html_document
---

__We uploaded the data from GitHub and tidy and transformed the data to perform analysis. We wanted to see what was the distance flown by the racing pigeons compared average (medal winning) historical bird distance.__

```{r}
library(dplyr)
library(knitr)
library(ggplot2)
library(ggthemes)

YB1_url <- read.csv(file="https://raw.githubusercontent.com/dbouquin/Pigeons/master/American_Racing_Pigeon_Union_Young_Bird_Data.csv", header=TRUE, sep=",")
OB_url <- read.csv(file="https://raw.githubusercontent.com/dbouquin/Pigeons/master/OldBirds.csv", header=TRUE, sep=",")
War_url <- read.csv(file="https://raw.githubusercontent.com/dbouquin/Pigeons/master/Dickin_Medal_Pigeons.csv", header=TRUE, sep=",")

head(YB1_url, 3)
head(OB_url, 3)

YB1_table <- data.frame(YB1_url[c(1, 5, 11, 13)])
YB1_table$TYPE <- "YOUNG BIRD (RACING PIGEONS)"
OB1_table <- data.frame(OB_url[c(2, 4, 12, 14)])
colnames(OB1_table)[1] <- "ORGANIZATION"
OB1_table$TYPE <- "OLD BIRD (RACING PIGEONS)"

Bird_table <- rbind.data.frame(YB1_table, OB1_table)
Bird_table$MILES <- as.numeric(format(Bird_table$MILES))

mile_tb <- subset(Bird_table, MILES > 1)
head(mile_tb)
mile_tb_total <- mile_tb %>% group_by(TYPE, ORGANIZATION) %>% summarise(AVERAGE_MILES = mean(MILES)) %>% data.frame()


mile_tb_total$ORGANIZATION[mile_tb_total$ORGANIZATION == "Wichita Friendly"] <- "Wichita Friendly Pigeon Flyers"
mile_tb_total$ORGANIZATION[mile_tb_total$ORGANIZATION == "Dallas"] <- "Dallas Homing RPC" 
mile_tb_total$ORGANIZATION[mile_tb_total$ORGANIZATION == "Evergreen State"] <- "Evergreen State Concourse" 
mile_tb_total$ORGANIZATION[mile_tb_total$ORGANIZATION == "75 Combines"] <- "75 Combine"

Medal_tb <- subset(War_url, Distance.mi. > 1)
Medal_tb_total <- Medal_tb %>%  summarise(AVERAGE_MILES = mean(Distance.mi.)) %>% data.frame()

head(Medal_tb)

TYPE <- "WAR PIGEONS"
ORGANIZATION <- "Dickin Medal Winners"
vec1 <- data.frame(TYPE, ORGANIZATION, Medal_tb_total)

Final_Bird_table <- rbind.data.frame(mile_tb_total, vec1)
Final_Bird_table$AVERAGE_MILES <- round(Final_Bird_table$AVERAGE_MILES, 1)
```


__Using `ggplot2`, `knitr`, and `ggthemes`, we created graph and table to compare the average distance flown by racing pigeons and Dickin medal winning pigeons.__
```{r}
kable(Final_Bird_table, align = "c", caption = "Average distance flown by racing pigeons today, compared to historical pigeons distance(medal winning).")

ggplot(data =  Final_Bird_table, aes(x=ORGANIZATION, y = AVERAGE_MILES, fill=TYPE)) + scale_colour_tableau()  + theme_solarized(light=FALSE) + theme(legend.position="top") + geom_bar(stat="identity", position = "dodge") + theme(axis.text.x  = element_text(angle=10, vjust=.9, hjust=.6)) + ggtitle(" Average distance flown by racing pigeons today, \ncompared to historical (medal winning) pigeons' distance.") + ylab("AVERAGE DISTANCE TRAVELED (MILES)")

````
